name: Python List

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      name: install Python
      uses: actions/setup python@v5
      with:
        python-version: "3.11"
      name: install flake8
      run: pip install flake8
      name: Run linter
      run: flake8 app/
